(#11477) tensorflow-lite/2.9.1
* [tensorflow-lite] Fixes for step-by-step package creation

* [tensorflow-lite] Removed redundant `get_safe`

* [tensorflow-lite] Replaced version-specific patches by extending CMake wrapper

* [tensorflow-lite] Removed ninja as build requirement, as it's not compulsory

(can be specified as build/tool requirement in a local profile if preferred)

* [tensorflow-lite] Removed restriction of `ruy` to shared when building `tensorflow-lite` as shared library

* [tensorflow-lite] Added tensorflow-lite v2.6.2

* [tensorflow-lite] Add tensorflow-lite v2.9.1

* [tensorflow-lite] Fix linter issues

Fix the issues called out by the linter in CI:

recipes/tensorflow-lite/all/conanfile.py:1: [W9006(conan-import-conanfile), ] Import ConanFile from new module: `from conan import ConanFile`. Old import is deprecated in Conan v2.
Error: recipes/tensorflow-lite/all/conanfile.py:111: [E1101(no-member), TensorflowLiteConan.source] Module 'conans.tools' has no 'get' member. Please, check https://github.com/conan-io/conan-center-index/blob/master/docs/v2_linter.md
recipes/tensorflow-lite/all/conanfile.py:117: [R1732(consider-using-with), TensorflowLiteConan.source] Consider using 'with' for resource-allocating operations
Warning: recipes/tensorflow-lite/all/conanfile.py:117: [W1514(unspecified-encoding), TensorflowLiteConan.source] Using open without explicitly specifying an encoding
recipes/tensorflow-lite/all/conanfile.py:119: [R1732(consider-using-with), TensorflowLiteConan.source] Consider using 'with' for resource-allocating operations
Warning: recipes/tensorflow-lite/all/conanfile.py:119: [W1514(unspecified-encoding), TensorflowLiteConan.source] Using open without explicitly specifying an encoding
recipes/tensorflow-lite/all/conanfile.py:156: [C0209(consider-using-f-string), TensorflowLiteConan._module_file] Formatting a regular string which could be a f-string
recipes/tensorflow-lite/all/conanfile.py:5: [E0611(no-name-in-module), ] No name 'ConanInvalidConfiguration' in module 'conans.errors'

* [tensorflow-lite] Remove pdb files for debug builds

* [tensorflow-lite] Use patches rather than patching dynamically

* [tensorflow-lite] Add explicit dependency on pthreadpool

pthreadpool is used by and linked to by xnnpack

* fixup! [tensorflow-lite] Fix linter issues

* fixup! [tensorflow-lite] Add tensorflow-lite v2.9.1

* [tensorflow-lite] Add patch_source to msvc patch

* [tensorflow-lite] Remove explicit pthreadpool dep, fix xnnpack dep

* [tensorflow-lite] Check for c++17 for 2.9.1 and above

* [tensorflow-lite] Remove remains of pthreadpool

* [tensorflow-lite] Patch CMakeLists instead of removing simple_memory_arena_debug_dump.cc

Co-authored-by: Gabriele Della Casa Venturelli <hardsetting@gmail.com>