(#14193) libcurl 7.86.0
* libcurl: add version 7.86.0

* libcurl: fix link failure in macOS test_package

Without this libcurl chokes at the test phase on macOS:

  Undefined symbols for architecture arm64:
    "_CFRelease", referenced from:
        _Curl_resolv in libcurl.a(libcurl_la-hostip.o)
  ld: symbol(s) not found for architecture arm64
  clang: error: linker command failed with exit code 1 (use -v to see invocation)

* libcurl: add patch_type and patch_description for linter

* libcurl: use rm_safe to clear unused options

* libcurl: only pass "--without-ssl" to autotools when it's true

As per https://github.com/curl/curl/commit/7d69924ce773f13c175e56ad1b20b0d5dac224b9

* libcurl: declare CoreFoundation framework dep for 7.78.0 onwards

https://github.com/curl/curl/commit/62be0960858f18798f5f2bf662cbfd9ae3948eb4

* libcurl: rework version checks as per code review

https://github.com/conan-io/conan-center-index/pull/14193#discussion_r1025364452
https://github.com/conan-io/conan-center-index/pull/14193#discussion_r1025386290

Co-authored-by: Josh Elsasser <josh@elsasser.ca>