(#4366) Add cpputest/4.0
* Copy in files from szip as a starting point

* Update versions for cpputest

* Copy in values for CppUTest

* Fix error:

ERROR: cpputest/4.0: Error in source() method, line 48
        tools.get(**self.conan_data["sources"][self.version])
        TypeError: get() argument after ** must be a mapping, not list

* Remove references to patches

* Remove reference to CMAKE_POSITION_INDEPENDENT_CODE

* Copy in test code from https://github.com/cpputest/conan-cpputest/blob/c4cf311e7b03de0ec8dfc89f2626b7ef172b7367/test_package/example.cpp

* Fix building of cpputest test package

* Remove remnant references to szip

* Fix inconsistent quoting of version numbers

* Second attempt at fixing quoting of version numbers

* Fix PC-FILES (KB-H020) by deleting lib/pkgconfig directory

* Fix CMAKE-MODULES-CONFIG-FILES (KB-H016) by deleting lib/CppUTest/cmake

* Add options

Copied in from:
https://github.com/cpputest/conan-cpputest/blob/c4cf311e7b03de0ec8dfc89f2626b7ef172b7367/conanfile.py

* Turn tests off, by default

* Update recipes/cpputest/all/conanfile.py

Co-authored-by: Chris Mc <prince.chrismc@gmail.com>

* Remove coverage and tests options - and force them to always be off.

Addressing code review feedback.

* Code review feedback: Fix use of find_package()

* Correct homepage URL to use https

* Remove unnecessary quotes in add_subdirectory() call

* Whitespace change: Fix inconsistent indentation

* Make default fPIC value consistent with majority of other recipes

* Code review feedback: Set pkg_config name

* Code review feedback: Remove unnecessary setting of self.cpp_info.filenames

* Attempt to fix Windows linker errors

LNK2019: unresolved external symbol __imp_timeGetTime

* Further attempt to fix Windows linker errors

LNK2019: unresolved external symbol __imp_timeGetTime

* Code review feedback: conditionally remove C++ settings

Co-authored-by: Chris Mc <prince.chrismc@gmail.com>

* Further attempt to fix Windows linker errors

LNK2019: unresolved external symbol __imp_timeGetTime

Fix taken from https://github.com/iimachines/webrtc-build/issues/2#issuecomment-503535704

Thanks to @prince-chrismc for pointing it out.

* Fix typo in configure()

* Remove ".lib" from library names, in further attempt to fix
missing __imp_timeGetTime symbol

* Remove verbose option - it doesn't affect the output library

* Make tests pass if extensions are disabled

* Invert if condition, to reduce nesting of code

* Further attempt at fixing missing symbols on Windows

* Another attempt at fixing missing symbols on Windows

* Revert back to the way of specifying winmm in b83b8da0f8daed0f898b6d40b6af2790ecfeee20

As this matches the

* Fix windows linker errors

* Delete fPIC option if shared

* Shared libraries are not supported, so remove that option

* Completely remove shared option, as shared builds not supported

* Code-review feedback: Remove commented-out lines

* Code-review feedback: Add pthread dependency on some platforms

* Add target CppUTest::CppUTestExt

* Make CppUTest::CppUTestExt depend on CppUTest::CppUTest

* Port remaining package_info() code to components

* Rename option extensions to with_extensions

* Rename option longlong to with_longlong

* Rename option detect_mem_leaks to detect_memory_leaks

* Remove all options except fPIC and with_extensions

* Remove empty method configure()

* Code review suggestion: "with_extensions" now uses [True, False]

Co-authored-by: Uilian Ries <uilianries@gmail.com>

Co-authored-by: Chris Mc <prince.chrismc@gmail.com>
Co-authored-by: Uilian Ries <uilianries@gmail.com>