(#4906) pango: bump gib and meson
* pango: bump gib and meson

* pango: disable gcc 4.9

because of undefined reference to `pthread_mutexattr_init'

* add required_conan_version