(#10315) libepoxy: set source charset to utf-8 fixing error C4819
* libepoxy: set source charset to utf-8 fixing error C4819

* libepoxy: use patches instead of meson arg

* libepoxy: fix styles

* Apply suggestions from code review

Co-authored-by: SpaceIm <30052553+SpaceIm@users.noreply.github.com>

Co-authored-by: SpaceIm <30052553+SpaceIm@users.noreply.github.com>