(#6337) OpenSSL on Windows: multi-profile support
```
ERROR: openssl/1.1.1k: Error in build() method, line 709
        env_vars = {"PERL": self._perl}
while calling '_perl', line 630
        return os.path.join(self.deps_cpp_info["strawberryperl"].rootpath, "bin", "perl.exe")
        KeyError: 'strawberryperl'
```

This is due to assuming `deps_cpp_info` is always available. As [documented](https://docs.conan.io/en/1.36/reference/conanfile/attributes.html#deps-user-info) this is only true for packages on the host context, while _strawberryperl_ is in the "build" context .

This change modifies _OpenSSL_, so it can be used in both ways.

Co-authored-by: Stefan Floeren <stefan-floeren@users.noreply.github.com>