Fix Linux Build, as libtool was not defined.
```
libsocketcan/0.0.12: Calling build()
libsocketcan/0.0.12: RUN: autoreconf --force --install
configure.ac:45: warning: The macro 'AC_HEADER_STDC' is obsolete.
configure.ac:45: You should run autoupdate.
/home/conan/workspace/cci_prod_PR-25786/conan-home/p/b/autoc14c7d1516d3b8/b/src/lib/autoconf/headers.m4:663: AC_HEADER_STDC is expanded from...
configure.ac:45: the top level
configure.ac:70: warning: The macro 'AC_HEADER_TIME' is obsolete.
configure.ac:70: You should run autoupdate.
/home/conan/workspace/cci_prod_PR-25786/conan-home/p/b/autoc14c7d1516d3b8/b/src/lib/autoconf/headers.m4:702: AC_HEADER_TIME is expanded from...
configure.ac:70: the top level
configure.ac:33: installing 'config/autoconf/compile'
configure.ac:10: installing 'config/autoconf/config.guess'
configure.ac:10: installing 'config/autoconf/config.sub'
configure.ac:36: installing 'config/autoconf/install-sh'
configure.ac:36: installing 'config/autoconf/missing'
src/GNUmakefile.am:1: error: Libtool library used but 'LIBTOOL' is undefined
src/GNUmakefile.am:1:   The usual way to define 'LIBTOOL' is to add 'LT_INIT'
src/GNUmakefile.am:1:   to 'configure.ac' and run 'aclocal' and 'autoconf' again.
src/GNUmakefile.am:1:   If 'LT_INIT' is in 'configure.ac', make sure
src/GNUmakefile.am:1:   its definition is in aclocal's search path.
src/GNUmakefile.am: installing 'config/autoconf/depcomp'
autoreconf: error: automake failed with exit status: 1

libsocketcan/0.0.12: ERROR:
Package 'b647c43bfefae3f830561ca202b6cfd935b56205' build failed
libsocketcan/0.0.12: WARN: Build folder /home/npustovoi/.conan2/p/b/libso54d0599d81851/b/build-release
ERROR: libsocketcan/0.0.12: Error in build() method, line 57
        autotools.autoreconf()
        ConanException: Error 1 while executing
```

Also pin autoconf to a specifc version, due to conflict with libtool.