(#16506) [rapidxml] Patch compilation issue with clang/gcc
* [rapidxml] Patch compilation issue with clang/gcc

Looks like a forward declaration issue, results in many compliation errors along the lines of:
```
/rapidxml_print.hpp:115:17: error: 'print_children' was not declared in this scope, and
no declarations were found by argument-dependent lookup at the point of instantiation [-fpermissive]
```

Issue was also reported here:
https://stackoverflow.com/questions/14113923/rapidxml-print-header-has-undefined-methods

Solution is to forward declare the various `print_` functions.

Also added use of `rapidxml_print.hpp` to verify that patch was applied correctly (will fail to compile otherwise).

* Add reference to original bug report

* Update required conan version