aws-sdk-cpp: fix recipe
Requirements were changed but this lib not, so it did not build with errors like
```
ERROR: Component 'aws-c-cal::aws-c-cal-lib' not found in 'aws-c-cal' package requirement
```