(#23126) Logfault header only library
* First take on a conan-recipe for logfault

This is my first submission to the conan-center-index.

* Corrected yaml indention

* Changed requirements. self.test_requires() failed with object has no attribute 'test_requires'

* Update recipes/logfault/all/conanfile.py

Co-authored-by: Rubén Rincón Blanco <git@rinconblanco.es>

* Update recipes/logfault/all/conanfile.py

Co-authored-by: Rubén Rincón Blanco <git@rinconblanco.es>

* Update recipes/logfault/all/conanfile.py

Co-authored-by: Rubén Rincón Blanco <git@rinconblanco.es>

* Update recipes/logfault/all/conanfile.py

Co-authored-by: Rubén Rincón Blanco <git@rinconblanco.es>

* Removed comments and 'def export_sources(self):' as suggested in code review.

* trying to fix build error: '... Check that you are using CMakeToolchain as generator to ensure its correct initialization'

* Update recipes/logfault/all/conanfile.py

Co-authored-by: Uilian Ries <uilianries@gmail.com>

* Update recipes/logfault/all/conanfile.py

Co-authored-by: Uilian Ries <uilianries@gmail.com>

* Update recipes/logfault/all/conanfile.py

Co-authored-by: Uilian Ries <uilianries@gmail.com>

* Update recipes/logfault/all/conanfile.py

Co-authored-by: Uilian Ries <uilianries@gmail.com>

* Update recipes/logfault/all/conanfile.py

Co-authored-by: Uilian Ries <uilianries@gmail.com>

* Changed cmake.test() to cmake.ctest(). There is no 'test' target.

* cmake.ctest() worked when I tested it locally, but failed v2_linter. Using cmake.test() with 'conan build .' with the original code checked out works. There is a 'test' target. Testing this receipie locally with 'conan create all/conanfile.py --version 0.5.0' fails because of a missing 'test' target. Changing the target of cmake.test() to 'all' works locally, and the test is executed. So trying that.

* Fixed problems with GTest link target in logfault code. Now pointing to version 0.5.1

Set tools.build:skip_test setting consistently to False. It was mixed, causing problems with test target.

* Updating version to 0.5.1

* Trying to restore the build by modifying the Cmake files in the origibnal code (bumpped to 0.5.2 to get a new tarball from github). Everything works fine locally and while building the original code with Github Actions on all platforms. But so it did for 0.5.1 as well.

* Disabling unit tests.

* Removed unit tests option

* Update recipes/logfault/all/test_package/CMakeLists.txt

Co-authored-by: Martin Valgur <martin.valgur@gmail.com>

* Update recipes/logfault/config.yml

Co-authored-by: Martin Valgur <martin.valgur@gmail.com>

* Removed 'generate' method.

---------

Co-authored-by: Rubén Rincón Blanco <git@rinconblanco.es>
Co-authored-by: Uilian Ries <uilianries@gmail.com>
Co-authored-by: Martin Valgur <martin.valgur@gmail.com>