(#22643) openssl: Add option to disable apps build in 3.x.x
This is useful for example to disable build of http_server for tvOS.

tvOS doesn't have fork() and http_server uses it:

apps/lib/http_server.c:156:24: error: 'fork' is unavailable: not available on tvOS
        switch (fpid = fork()) {