(#6891) Add nmos-cpp
* nmos-cpp recipe files copied from https://github.com/sony/nmos-cpp/pull/195

* Add config.yml for current tip of garethsb:library-cmake

* Attempt to install Avahi Apple Bonjour compatibility library on Linux

* Provide with_dnssd options based on #6928, #6930, #6937

* Fix typo in prev commit

* Simplify selection of appropriate requirements for DNS-SD

* For now, keep default option as mdnsresponder on Windows and Linux

* Leave most exceptions uncaught as they really aren't expected in the test_package (cf. the best practice shown in nmos-cpp-node example app) but do catch web::http::http_exception since the most likely cause of that is a port being in use or, on Windows with cpprestsdk built with its default settings, that the test_package wasn't run as administrator, which WinHTTP enforces to listen on the wildcard hostname.
Uncaught exceptions, via std::terminate, end up as STATUS_STACK_BUFFER_OVERRUN on Windows (see https://devblogs.microsoft.com/oldnewthing/20190108-00/?p=100655), which Conan reports as "ConanException: Error 3221226505 while executing bin\test_package", which might take one a while to understand, if one didn't already know all of this...

* Update to head revision of garethsb:library-cmake and latest mdnsresponder (#6930) and avahi (#7049) from-source recipes, since those seem more likely to be approved on CCI

* Better comment

* Switch to upstream sony/nmos-cpp
(https://github.com/sony/nmos-cpp/pull/195 was merged to master)

* self.options.get_safe("with_dnssd")

* For now, to build on CCI, don't require the opt-in patches

* Build requires CMake 3.17

* Hopefully using short paths will resolve "fatal error C1083: Cannot open compiler generated file: '': Invalid argument" on some Windows builds on CCI

* Test package requires C++11

* int64_t should work everywhere... I think

* Test proposed upstream fix to make relocatable package per https://cmake.org/cmake/help/latest/manual/cmake-packages.7.html#creating-relocatable-packages

* Fix handling of ${_IMPORT_PREFIX}

* Fix handling of ${_IMPORT_PREFIX} and add tools.check_min_cppstd

* No version ranges

* Log all exceptions
to debug intermittent test_package failure on arch=x86_64, build_type=Release, compiler=Visual Studio, compiler.runtime=MT, compiler.version=14, os=Windows

* Additional warning

* Take upstream latest which merged the relocatable package fix (cf. bf1388a6)

* Update conanfile.py

* Apply suggestions from code review (properly)

Co-authored-by: Anonymous Maarten <madebr@users.noreply.github.com>

* Apply suggestions from code review

Co-authored-by: Anonymous Maarten <madebr@users.noreply.github.com>

* Apply suggestions from code review

Co-authored-by: Anonymous Maarten <madebr@users.noreply.github.com>

* self.options["mdnsresponder"].with_opt_patches = True

* Apply suggestions from code review

Co-authored-by: Uilian Ries <uilianries@gmail.com>

* cmake/3.21.1 conflicts with openssl/1.1.1l

* Update topics

* Try bump openssl/1.1.1l and cmake/3.21.2

* Take upstream latest, now built and tested with OpenSSL v1.1.1L

Co-authored-by: Anonymous Maarten <madebr@users.noreply.github.com>
Co-authored-by: Uilian Ries <uilianries@gmail.com>