opentelemetry-cpp: fix visibility of protobuf and gRPC headers
Protobuf and gRPC headers must be made available for consumers of the
OpenTelemetry package because the generated headers for OTLP refer to
them.

This fixes the following compiler errors downstream:

```
In file included from $HOME/.conan2/p/b/opent272c3e9f1254c/p/include/opentelemetry/exporters/otlp/otlp_grpc_exporter.h:11:
In file included from $HOME/.conan2/p/b/opent272c3e9f1254c/p/include/opentelemetry/proto/collector/trace/v1/trace_service.grpc.pb.h:22:
$HOME/.conan2/p/b/opent272c3e9f1254c/p/include/opentelemetry/proto/collector/trace/v1/trace_service.pb.h:10:10: fatal error: 'google/protobuf/port_def.inc' file not found
```

```
In file included from $HOME/.conan2/p/b/opentde6f16d8c2837/p/include/opentelemetry/exporters/otlp/otlp_grpc_exporter.h:11:
$HOME/.conan2/p/b/opentde6f16d8c2837/p/include/opentelemetry/proto/collector/trace/v1/trace_service.grpc.pb.h:25:10: fatal error: 'grpcpp/generic/async_generic_service.h' file not found
```