(#3443) Add pdal/2.2.0
* Add pdal 2.2.0

* Cache cmake, move patching

* Link test to pdal target

* Patch missing stdexcept header

* Use find_package in module mode

* Patch missing cstdlib header

* Add TODOs for improvements

* Add dependency to libunwind

* Use CCI nanoflann instead of vendored

* Makr gcc49 as unsupported due to std::get_time

* Fix VC16 build error

* Trying to fix VS2019 error

error C2678: binary '=': no operator found which takes a left-hand
operand of type 'const pdal::PointViewIter::reference'
while trying to match the argument list '(const pdal::PointViewIter::reference, pdal::PointRef)

* Fix patches for a single file

* Do not set CMAKE_POSITION_INDEPENDENT_CODE manually

Co-authored-by: Uilian Ries <uilianries@gmail.com>

* Use shared by default

Co-authored-by: Uilian Ries <uilianries@gmail.com>

* Fix license name

Co-authored-by: Uilian Ries <uilianries@gmail.com>

* Add patch comments

* Allow shared option to be only true

* Clarify shared option

* Bring back boolean shared option

Co-authored-by: Uilian Ries <uilianries@gmail.com>