glib: add components (#2304)
* glib: add components

* fix executable component

without this, we get this error:
ERROR: Generator cmake(file:conanbuildinfo.cmake) failed
'gresource'
ERROR: 'gresource'

* test glib components with cmake

* test glib components with pkg-config

* log PATH env var appending

* Revert "test glib components with pkg-config"

This reverts commit d9d9fcb4f4a9e51065577c857312f5a2e72844a9.

* test with cmake_find_package