(#18483) openblas: fix error with build_lapack option
If `build_lapack` was set to `True`, you would get the following error:

```
ERROR: openblas/0.3.15: Error in generate() method, line 79
	self.output.warn("Building with lapack support requires a Fortran compiler.")
	AttributeError: 'ConanOutput' object has no attribute 'warn'
```