(#8347) behaviortree.cpp: fix unportable use of PRId64
The original error in some version of gcc:

    error: expected ``)' before 'PRIu64'

To use PRId64 and be portable, we need to define the macro
`__STDC_FORMAT_MACROS` before `inttypes.h` was included.