(#4452) hazelcastcxx 4.0.0 recipe
* Added hazelcastcxx recipe.

* Fixed the default value of "shared" option.

* Added verbose output to test_package build.

* For gcc compiler set the package_test cppstd as "libstdc++11" since out library build uses the new ABI format. See https://docs.conan.io/en/latest/howtos/manage_gcc_abi.html .

* For Linux environment with clang compiler, set the package_test cppstd as "libstdc++11" since our library build uses the new ABI format.

* Updated the cmake file for the test_package to force use C++11 standard.

* Do not support linux configuration where "compiler.libcxx != libstdc++11"

Also updated boost dependency as the minimum version to be 1.71.0.

* Set the run-time library correctly for Visual Studio compiler. Otherwise, we see runtime library mismatch errors such as:

`hazelcastcxx_static.lib(client_impl.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MDd_DynamicDebug' doesn't match value 'MTd_StaticDebug' in test_package.obj`

* Added flag "/EHsc" for Visual Studio build to fix error `fatal error C1189: #error:  This header requires exception handling to be enabled.`

* Added CMAKE_CXX_FLAGS_DEBUG and CMAKE_CXX_FLAGS_RELEASE for Visual Studio compilation.

* Work around MSVC /MT /MD flag fix as provided by the example in the documentation.

* Apply suggestions from code review

Co-authored-by: Chris Mc <prince.chrismc@gmail.com>

* Review comment fixes.

Changed the test_package to use find_package command to test.

* Review comment fixes.

* Renamed the recipe folder name to fix the CI build error:

```
ERROR: Package recipe with name hazelcastcxx!=hazelcast-cpp-client
```

* Apply suggestions from code review

Co-authored-by: Chris Mc <prince.chrismc@gmail.com>

* Review comment fixes.

* Fix to the incorrect install directory usage of the Hazelcast project.

* Replaced the work around of using `replace_in_file` with using a patch.

* Apply suggestions from code review

Co-authored-by: Yoann Potinet <intelligide@hotmail.fr>

Co-authored-by: Chris Mc <prince.chrismc@gmail.com>
Co-authored-by: Yoann Potinet <intelligide@hotmail.fr>