(#23281) Use (ftp.gnu.org) as fallback of (ftpmirror.gnu.org), as the second might fail due to unsafe crypto
* Don't use ftpmirror.gnu.org, as it might fail

With the departure towards OpenSSL some mirrors are still using old unsafe renegotiation, and that's preventing from building this recipe.

I have noticed the mirror here about the issue, but from the time being it's just better to use the non mirrored FTP.

autoconf/2.71: ERROR: Error downloading file https://ftpmirror.gnu.org/autoconf/autoconf-2.71.tar.xz: 'HTTPSConnectionPool(host='ftp.rediris.es', port=443): Max retries exceeded with url: /mirror/GNU/autoconf/autoconf-2.71.tar.xz (Caused by SSLError(SSLError(1, '[SSL: UNSAFE_LEGACY_RENEGOTIATION_DISABLED] unsafe legacy renegotiation disabled (_ssl.c:1006)')))'
ERROR: autoconf/2.71: Error in source() method, line 51
        get(self, **self.conan_data["sources"][self.version], strip_root=True)
        ConanException: Error downloading file https://ftpmirror.gnu.org/autoconf/autoconf-2.71.tar.xz: 'HTTPSConnectionPool(host='ftp.rediris.es', port=443): Max retries exceeded with url: /mirror/GNU/autoconf/autoconf-2.71.tar.xz (Caused by SSLError(SSLError(1, '[SSL: UNSAFE_LEGACY_RENEGOTIATION_DISABLED] unsafe legacy renegotiation disabled (_ssl.c:1006)')))'

* autoconf/all/conandata.yml: fallback urls: v2.72

Co-authored-by: Martin Valgur <martin.valgur@gmail.com>

* autoconf/all/conandata.yml: fallback urls: v2.71

Co-authored-by: Martin Valgur <martin.valgur@gmail.com>

* autoconf: conandata.yml: Lint urls properly

---------

Co-authored-by: Martin Valgur <martin.valgur@gmail.com>