fix: option 'docbook' doesn't exist in 2.10.3
ERROR: libxml2/2.10.3: option 'docbook' doesn't exist
Possible options are ['shared', 'fPIC', 'include_utils', 'c14n', 'catalog', 'ftp', 'http', 'html', 'iconv', 'icu', 'iso8859x', 'legacy', 'mem-debug', 'output', 'pattern', 'push', 'python', 'reader', 'regexps', 'run-debug', 'sax1', 'schemas', 'schematron', 'threads', 'tree', 'valid', 'writer', 'xinclude', 'xpath', 'xptr', 'zlib', 'lzma']