thrift: bump zlib version
thrift packages are currently broken due to the new zlib 1.2.12 version. For instance:
````bash
WARN: boost/1.78.0: requirement zlib/1.2.12 overridden by thrift/0.15.0 to zlib/1.2.11
ERROR: Conflict in c-blosc/1.20.1:
    'c-blosc/1.20.1' requires 'zlib/1.2.12' while 'thrift/0.15.0' requires 'zlib/1.2.11'.
    To fix this conflict you need to override the package 'zlib' in your root package.
````