(#23838) eudev: Bump libxslt to avoid conflicts
Fixes the following error:

ERROR: Version conflict: libxslt/1.1.34->libxml2/2.11.6, eudev/3.2.14->libxml2/2.12.6.