(#13585) screen_capture_lite: add recipe
* screen_capture_lite: add recipe

* apply patch

* remove unused modules

* fix wrong recipe folder name

* cast bool

* downgrade cmake minimum required

* drop support clang with libstdc++

* try to fix error C2039

* link d3dll, dxgi on Windows

* delete invalid unescaped character

* fix typo

* specify CMAKE_SYSTEM_VERSION on Windodws

* remove pdb files

* link AppKit, ImageIO, Foundation

* remove importing is_msvc and VirtualBuildEnv

Co-authored-by: Uilian Ries <uilianries@gmail.com>

* remove BUILD_SHARED_LIBS from upstream CMakeLists.txt

Co-authored-by: Uilian Ries <uilianries@gmail.com>