(#13499) glaze: add recipe
* glaze: add recipe

* fix license filename

* update required gcc version

* update required gcc version

* update required conan version

Co-authored-by: SpaceIm <30052553+SpaceIm@users.noreply.github.com>

* update to 0.0.7

* update compiler minimum version

* drop support apple-clang

* only libdirs is set empty

Co-authored-by: SpaceIm <30052553+SpaceIm@users.noreply.github.com>

* fix recipe name

Co-authored-by: SpaceIm <30052553+SpaceIm@users.noreply.github.com>

* update conan version

Co-authored-by: SpaceIm <30052553+SpaceIm@users.noreply.github.com>

* support apple-clang >= 13.1

* use loose_lt_semvar

* fix _min_cppstd

* try to fix error C2039

* revert test_package

Co-authored-by: SpaceIm <30052553+SpaceIm@users.noreply.github.com>