(#13361) sdl_image: build improvements for ImageIO option for Apple platforms
* fix shared macOS build with ImageIO

* add required frameworks to cpp_info in static macOS build with ImageIO

* allow other Apple platforms to be built with ImageIO

* update libjpeg dependency to 9e

fixes CI build error:
WARN: libtiff/4.4.0: requirement libjpeg/9e overridden by sdl_image/2.0.5 to libjpeg/9d
ERROR: Missing binary: libtiff/4.4.0:f82ef25da4e9f661f118d3aa44ad6c1bfef0bc79