[tensorflow-lite] Fix linter issues
Fix the issues called out by the linter in CI:

recipes/tensorflow-lite/all/conanfile.py:1: [W9006(conan-import-conanfile), ] Import ConanFile from new module: `from conan import ConanFile`. Old import is deprecated in Conan v2.
Error: recipes/tensorflow-lite/all/conanfile.py:111: [E1101(no-member), TensorflowLiteConan.source] Module 'conans.tools' has no 'get' member. Please, check https://github.com/conan-io/conan-center-index/blob/master/docs/v2_linter.md
recipes/tensorflow-lite/all/conanfile.py:117: [R1732(consider-using-with), TensorflowLiteConan.source] Consider using 'with' for resource-allocating operations
Warning: recipes/tensorflow-lite/all/conanfile.py:117: [W1514(unspecified-encoding), TensorflowLiteConan.source] Using open without explicitly specifying an encoding
recipes/tensorflow-lite/all/conanfile.py:119: [R1732(consider-using-with), TensorflowLiteConan.source] Consider using 'with' for resource-allocating operations
Warning: recipes/tensorflow-lite/all/conanfile.py:119: [W1514(unspecified-encoding), TensorflowLiteConan.source] Using open without explicitly specifying an encoding
recipes/tensorflow-lite/all/conanfile.py:156: [C0209(consider-using-f-string), TensorflowLiteConan._module_file] Formatting a regular string which could be a f-string
recipes/tensorflow-lite/all/conanfile.py:5: [E0611(no-name-in-module), ] No name 'ConanInvalidConfiguration' in module 'conans.errors'