boost: add with_stacktrace_addr2line option
While attempting to cross-compile Boost for the x86 architecture
using a multilib toolchain I have the follwoing error:
boost/1.84.0: WARN: Boost component 'stacktrace_addr2line' is missing libraries. Try building boost with '-o boost:without_stacktrace_addr2line'. (Option is not guaranteed to exist)
boost/1.84.0: WARN: Boost component 'stacktrace_backtrace' is missing libraries. Try building boost with '-o boost:without_stacktrace_backtrace'. (Option is not guaranteed to exist)
ERROR: boost/1.84.0: Error in package_info() method, line 1750
        raise ConanException(f"These libraries were expected to be built, but were not built: {non_built}")
        ConanException: These libraries were expected to be built, but were not built: {'boost_stacktrace_backtrace', 'boost_stacktrace_addr2line'}

To address this issue, I've introduced the 'with_stacktrace_addr2line' option.

This modification allows explicitly disable the inclusion of
'boost_stacktrace_addr2line' during the build process. By doing so,
it allows Boost to be built with alternative stacktrace options, such as
'boost_stacktrace_noop' and 'boost_stacktrace_basic'.

Signed-off-by: Artem Panfilov <artem.panfilov@nokia.com>